

// UI 번역 dictionary (KOR / ENG)
// 모든 하드코딩된 UI 텍스트 관리  (파일생성 및 변경 : AI 도움 => 서브기능)


export type Lang = 'ko' | 'en';

export const T: Record<string, { ko: string; en: string }> = {

  // ── 네비게이션 (Header 메인 탭) ──
  navGrades:           { ko: '학점관리',             en: 'Grades'              },
  navBoard:            { ko: '게시판',                en: 'Board'               },
  navCourses:          { ko: '수강신청 관리',          en: 'Courses'             },

  // ── Header 드롭다운 ──
  menuSettings:        { ko: '설정',                  en: 'Settings'            },
  menuReupload:        { ko: '성적표 재업로드',         en: 'Re-upload Transcript'},
  menuLogout:          { ko: '로그아웃',               en: 'Sign Out'            },
  menuWithdraw:        { ko: '회원 탈퇴',              en: 'Delete Account'      },
  noDeptInfo:          { ko: '학과 정보 없음',          en: 'No dept info'        },
  withdrawConfirm:     { ko: '정말 탈퇴하겠습니까?\n모든 데이터가 삭제되며 복구할 수 없습니다.',
                         en: 'Delete your account?\nAll data will be permanently deleted and cannot be recovered.' },

  // ── 설정 팝업 ──
  settingsTitle:       { ko: '설정',                  en: 'Settings'            },
  darkMode:            { ko: '다크 모드',              en: 'Dark Mode'           },
  close:               { ko: '닫기',                  en: 'Close'               },

  // ── Sidebar ──
  sideGradesSection:   { ko: '학점관리',               en: 'GRADES'              },
  sideDashboard:       { ko: '대시보드',               en: 'Dashboard'           },
  sideCredits:         { ko: '학점현황',               en: 'Credits'             },
  sideTimetable:       { ko: '시간표',                 en: 'Timetable'           },
  sideAI:              { ko: 'AI 성적분석',             en: 'AI Analysis'         },
  sideBoardSection:    { ko: '게시판',                 en: 'BOARD'               },
  sideBoard:           { ko: '게시판',                 en: 'Board'               },
  sideCoursesSection:  { ko: '수강신청 관리',           en: 'COURSES'             },
  sideCoursesBtn:      { ko: '수강신청',               en: 'Courses'             },
  sideSemSummary:      { ko: '이번 학기 요약',           en: 'SEMESTER SUMMARY'    },
  sideCumGPA:          { ko: '누적 GPA',               en: 'Cum. GPA'            },
  sideThisSem:         { ko: '이번 학기',              en: 'This Sem'            },
  sideGradCredits:     { ko: '졸업학점',               en: 'Grad Credits'        },
  sideUpcoming:        { ko: '다가오는 일정',            en: 'UPCOMING'            },
  sideNoEvents:        { ko: '일정 없음',              en: 'No events'           },
  sideCollapse:        { ko: '접기',                  en: 'Collapse'            },

  // ── PageNav 탭 ──
  tabDashboard:        { ko: '대시보드',               en: 'Dashboard'           },
  tabCredits:          { ko: '학점현황',               en: 'Credits'             },
  tabTimetable:        { ko: '시간표',                 en: 'Timetable'           },
  tabAI:               { ko: 'AI 성적분석',             en: 'AI Analysis'         },

  // ── 공통 버튼 / 액션 ──
  loading:             { ko: '불러오는 중...',           en: 'Loading...'          },
  cancel:              { ko: '취소',                  en: 'Cancel'              },
  save:                { ko: '저장',                  en: 'Save'                },
  add:                 { ko: '+ 추가',                en: '+ Add'               },
  addCourse:           { ko: '+ 과목 추가',             en: '+ Add Course'        },
  edit:                { ko: '수정',                  en: 'Edit'                },
  delete:              { ko: '삭제',                  en: 'Delete'              },
  done:                { ko: '완료',                  en: 'Done'                },
  noData:              { ko: '데이터 없음',             en: 'No data'             },
  viewAll:             { ko: '전체보기',               en: 'View All'            },

  // ── 과목 구분 (드롭다운 표시용, DB value는 한국어 유지) ──
  catReqMajor:         { ko: '전공필수',               en: 'Req. Major'          },
  catElectMajor:       { ko: '전공선택',               en: 'Elect. Major'        },
  catReqLib:           { ko: '교양필수',               en: 'Req. Liberal'        },
  catElectLib:         { ko: '교양선택',               en: 'Elect. Liberal'      },

  // ── Dashboard ──
  dashCumGPA:          { ko: '누적 성적',              en: 'Cumulative GPA'      },
  dashPercentile:      { ko: '백분율',                 en: 'Percentile'          },
  dashMajor:           { ko: '전공',                  en: 'Major'               },
  dashLiberal:         { ko: '교양',                  en: 'Liberal'             },
  dashBest:            { ko: '최고',                  en: 'Best'                },
  dashWorst:           { ko: '최저',                  en: 'Worst'               },
  dashAvg:             { ko: '평균',                  en: 'Avg'                 },
  dashTarget:          { ko: '목표',                  en: 'Target'              },
  dashEnrolled:        { ko: '등록',                  en: 'Enrolled'            },
  dashSems:            { ko: '학기',                  en: 'sems'                },
  dashSubjectUnit:     { ko: '과목',                  en: 'courses'             },
  dashEarnedCr:        { ko: '이수학점',               en: 'Credits'             },
  dashTargetGPA:       { ko: '목표 GPA',              en: 'Target GPA'          },
  dashCurrentPrefix:   { ko: '현재 ',                 en: 'Curr '               },
  dashAchieved:        { ko: '달성 ✓',                en: 'Achieved ✓'          },
  dashAchievable:      { ko: '달성 가능',              en: 'Achievable'          },
  dashShortSuffix:     { ko: ' 부족',                 en: ' short'              },
  dashRemainSuffix:    { ko: '학점 잔여',              en: 'cr left'             },
  dashRemainShort:     { ko: ' 잔여',                 en: ' left'               },
  dashDone:            { ko: '완료 ✓',                en: 'Done ✓'              },
  dashDoneSimple:      { ko: '완료',                  en: 'Done'                },
  dashSemGrades:       { ko: '학기별 성적',             en: 'Semester Grades'     },
  dashAddSem:          { ko: '+ 학기 추가',             en: '+ Add Semester'      },
  dashGpaTrend:        { ko: '학기별 GPA 추이',         en: 'GPA Trend'           },
  dashGoalLine:        { ko: '목표',                  en: 'Goal'                },
  dashGradeDistrib:    { ko: '성적 분포 · 전체 이수 과목', en: 'Grade Distribution'  },
  dashCompletedN:      { ko: '완료',                  en: 'Completed'           },
  dashBelowC:          { ko: 'C이하',                 en: 'Below C'             },
  dashCurrentSem:      { ko: '현재 학기',              en: 'Current Sem'         },
  dashPending:         { ko: '성적 발표 전',            en: 'Awaiting grades'     },
  dashProjected:       { ko: '이번학기 예상',            en: 'Projected'           },
  dashCurrentShort:    { ko: '현재',                  en: 'Current'             },
  dashTargetShort:     { ko: '목표',                  en: 'Target'              },
  dashExpectedChart:   { ko: '예상',                  en: 'Est.'                },
  dashGradeInput:      { ko: '과목별 성적 입력',         en: 'Enter Grades'        },
  dashAll:             { ko: '전체',                  en: 'All'                 },
  dashCompleteSem:     { ko: '이번 학기 완료 처리',       en: 'Complete Semester'   },
  dashNoCourses:       { ko: '강의 데이터 없음',          en: 'No courses'          },
  dashCourseNamePh:    { ko: '과목명 입력',              en: 'Course name'         },
  dashAddBtn:          { ko: '+ 추가',                en: '+ Add'               },
  dashTargetGrades:    { ko: '목표 성적',              en: 'Target Grades'       },
  dashSemTargets:      { ko: '이번 학기 과목별 목표',      en: 'Semester Targets'    },
  dashNotSet:          { ko: '목표 미설정',             en: 'Not set'             },
  dashNoCourseList:    { ko: '수강 과목 없음',           en: 'No courses'          },
  dashGoalResult:      { ko: '목표대로 받으면 이번학기 ', en: 'If on target, this sem ' },
  dashGoalAchieved:    { ko: '→ 목표 달성 ✓',           en: '→ Goal achieved ✓'   },
  dashGoalMissed:      { ko: '→ 목표 미달',             en: '→ Below target'      },
  dashThisSemCourses:  { ko: '이번 학기 수강',           en: 'This Semester'       },
  dashCourseName:      { ko: '과목명',                 en: 'Course'              },
  dashType:            { ko: '구분',                  en: 'Type'                },
  dashCredits:         { ko: '학점',                  en: 'Cr'                  },
  dashTotalCredits:    { ko: '총',                    en: 'Total'               },
  dashScheduleCard:    { ko: '시간표',                 en: 'Schedule'            },
  dashNoClasses:       { ko: '등록된 수업 없음',          en: 'No classes'          },
  dashDayMon:          { ko: '월',                    en: 'Mon'                 },
  dashDayTue:          { ko: '화',                    en: 'Tue'                 },
  dashDayWed:          { ko: '수',                    en: 'Wed'                 },
  dashDayThu:          { ko: '목',                    en: 'Thu'                 },
  dashDayFri:          { ko: '금',                    en: 'Fri'                 },
  dashCreditsStatus:   { ko: '학점 이수 현황',           en: 'Credits Status'      },
  dashTotalEarned:     { ko: '총 이수',                en: 'Earned'              },
  dashCreditsUnit:     { ko: '학점',                  en: 'cr'                  },
  dashMajorCredits:    { ko: '전공학점',               en: 'Major Credits'       },
  dashNoGradReq:       { ko: '졸업요건 미설정',          en: 'No grad req.'        },
  dashArea:            { ko: '영역',                  en: 'Area'                },
  dashEarned:          { ko: '이수',                  en: 'Earned'              },
  dashRequired:        { ko: '기준',                  en: 'Req.'                },
  dashProgress:        { ko: '진행률',                en: 'Progress'            },
  dashLiberalCr:       { ko: '교양학점',               en: 'Liberal Arts Cr.'    },
  dashStatus:          { ko: '상태',                  en: 'Status'              },
  dashSem1:            { ko: '1학기',                 en: 'Sem 1'               },
  dashSem2:            { ko: '2학기',                 en: 'Sem 2'               },
  dashSummer:          { ko: '하계',                  en: 'Summer'              },
  dashWinter:          { ko: '동계',                  en: 'Winter'              },
  dashCoursesHeader:   { ko: '수강 과목',              en: 'Courses'             },
  dashOptional:        { ko: '선택',                  en: 'optional'            },
  dashGrade:           { ko: '성적',                  en: 'Grade'               },
  dashAddCourseHint:   { ko: '과목을 추가하면 학기 내역에 표시됩니다.',
                         en: 'Add courses to show in semester.'                },
  dashEditTargetGPA:   { ko: '목표 GPA 수정',           en: 'Edit Target GPA'     },
  dashGPARange:        { ko: '0.00 ~ 4.50 범위 내로 입력해주세요.',
                         en: 'Enter a value between 0.00 and 4.50.'           },
  dashGradStatus:      { ko: '졸업 현황',              en: 'Graduation'          },
  dashGradPctLabel:    { ko: '졸업 학점 달성률',         en: 'Credit Achievement'  },
  dashRemSems:         { ko: '잔여 학기',              en: 'Semesters left'      },
  dashSemUnit:         { ko: '학기',                  en: ''                    },
  dashGradCert:        { ko: '졸업인증',               en: 'Grad Cert.'          },
  dashIncomplete:      { ko: '미완료',                en: 'Incomplete'          },
  dashNoGradeData:     { ko: '성적 데이터가 없습니다',    en: 'No grade data'       },
  dashAlertMid:        { ko: '중간성적 입력 마감',        en: 'Midterm Grade Deadline'},
  dashSemInfoLabel:    { ko: '2025년 1학기 · 소프트웨어학부', en: '2025 Sem 1 · Software Dept.' },

  // ── Credits 페이지 ──
  credRemaining:       { ko: '이수 잔여 항목',           en: 'Remaining Items'     },
  credGradProgress:    { ko: '졸업 달성률',             en: 'Graduation Progress' },
  credEarned:          { ko: '이수',                  en: 'Earned'              },
  credLeft:            { ko: '잔여',                  en: 'Remaining'           },
  credMajor:           { ko: '전공',                  en: 'Major'               },
  credLiberal:         { ko: '교양',                  en: 'Liberal'             },
  credGradCert:        { ko: '졸업인증',               en: 'Grad Cert.'          },
  credDone:            { ko: '완료',                  en: 'Done'                },
  credIncomplete:      { ko: '미완료',                en: 'Incomplete'          },
  credMajorSection:    { ko: '전공',                  en: 'Major'               },
  credLibSection:      { ko: '필수 교양',              en: 'Req. Liberal Arts'   },
  credReqStatus:       { ko: '졸업 요건 현황',           en: 'Grad Requirements'   },
  credAddItem:         { ko: '+ 항목 추가',             en: '+ Add Item'          },
  credIncompleteN:     { ko: '개 미완료',              en: ' incomplete'         },
  credItemName:        { ko: '항목명 (예: 영어 공인 성적)', en: 'Name (e.g. English score)' },
  credItemReq:         { ko: '기준 (예: 토익 700+)',     en: 'Req. (e.g. TOEIC 700+)' },
  credAddBtn:          { ko: '추가',                  en: 'Add'                 },
  credNoItems:         { ko: '항목이 없습니다. 엑셀 업로드 또는 직접 추가하세요.',
                         en: 'No items. Upload Excel or add manually.'         },
  credDoneMark:        { ko: '완료 ✓',                en: 'Done ✓'              },
  credArea:            { ko: '영역',                  en: 'Area'                },
  credEarnedCol:       { ko: '이수',                  en: 'Earned'              },
  credReqCol:          { ko: '기준',                  en: 'Req.'                },
  credProgressCol:     { ko: '진행률',                en: 'Progress'            },
  credCrLeft:          { ko: '학점 잔여',              en: 'cr left'             },
  credCrUnit:          { ko: '학점',                  en: 'cr'                  },

  // ── Timetable ──
  ttTimetableTab:      { ko: '시간표',                en: 'Timetable'           },
  ttAddScheduleTab:    { ko: '일정 추가',              en: 'Add Event'           },
  ttMon:               { ko: '월',                    en: 'Mon'                 },
  ttTue:               { ko: '화',                    en: 'Tue'                 },
  ttWed:               { ko: '수',                    en: 'Wed'                 },
  ttThu:               { ko: '목',                    en: 'Thu'                 },
  ttFri:               { ko: '금',                    en: 'Fri'                 },
  ttMonFull:           { ko: '월요일',                en: 'Monday'              },
  ttTueFull:           { ko: '화요일',                en: 'Tuesday'             },
  ttWedFull:           { ko: '수요일',                en: 'Wednesday'           },
  ttThuFull:           { ko: '목요일',                en: 'Thursday'            },
  ttFriFull:           { ko: '금요일',                en: 'Friday'              },
  ttTypeReqMajor:      { ko: '전공필수',               en: 'Req. Major'          },
  ttTypeElectMajor:    { ko: '전공선택',               en: 'Elect. Major'        },
  ttTypeLib:           { ko: '교양',                  en: 'Liberal'             },
  ttTypeOther:         { ko: '기타',                  en: 'Other'               },
  ttDuplicateError:    { ko: '기존 수업을 먼저 삭제한 후 다시 추가해 주세요.',
                         en: 'Please delete the existing class first, then add again.' },
  ttMyTimetable:       { ko: '이번학기 시간표',          en: 'My Timetable'        },
  ttAddClass:          { ko: '수업 추가',              en: 'Add Class'           },
  ttCourses:           { ko: '수강 과목',              en: 'Courses'             },
  ttNoClasses:         { ko: '등록된 수업이 없습니다',    en: 'No classes yet'      },
  ttUpcoming:          { ko: '다가오는 일정',            en: 'Upcoming Events'     },
  ttNoEvents:          { ko: '등록된 일정이 없습니다',    en: 'No events yet'       },
  ttAddEvent:          { ko: '새 일정 추가',             en: 'Add Event'           },
  ttTitle:             { ko: '제목',                  en: 'Title'               },
  ttTitlePh:           { ko: '일정 제목을 입력하세요.',   en: 'Event title'         },
  ttDate:              { ko: '날짜',                  en: 'Date'                },
  ttTime:              { ko: '시간',                  en: 'Time'                },
  ttCategory:          { ko: '분류',                  en: 'Category'            },
  ttAssignment:        { ko: '과제',                  en: 'Assignment'          },
  ttExam:              { ko: '시험',                  en: 'Exam'                },
  ttPresentation:      { ko: '발표',                  en: 'Presentation'        },
  ttProject:           { ko: '프로젝트',               en: 'Project'             },
  ttOther:             { ko: '기타',                  en: 'Other'               },
  ttMemo:              { ko: '메모',                  en: 'Memo'                },
  ttOptional:          { ko: '(선택)',                en: '(optional)'          },
  ttMemoPh:            { ko: '메모를 입력하세요...',     en: 'Add a memo...'       },
  ttSaveEvent:         { ko: '일정 저장',              en: 'Save Event'          },
  ttMyEvents:          { ko: '내 일정 목록',            en: 'My Events'           },
  ttAddClassTitle:     { ko: '수업 추가',              en: 'Add Class'           },
  ttCourseName:        { ko: '과목명',                en: 'Course Name'         },
  ttCourseNamePh:      { ko: '예: 자료구조',            en: 'e.g. Data Structures'},
  ttDay:               { ko: '요일',                  en: 'Day'                 },
  ttStart:             { ko: '시작',                  en: 'Start'               },
  ttEnd:               { ko: '종료',                  en: 'End'                 },
  ttType:              { ko: '구분',                  en: 'Type'                },
  ttNewClass:          { ko: '새 수업',               en: 'New Class'           },
  ttEvAssignment:      { ko: '과제',                  en: 'Assignment'          },
  ttEvExam:            { ko: '시험',                  en: 'Exam'                },
  ttEvPresentation:    { ko: '발표',                  en: 'Presentation'        },
  ttEvProject:         { ko: '프로젝트',               en: 'Project'             },
  ttEvOther:           { ko: '기타',                  en: 'Other'               },

  // ── AI Analysis ──
  aiTitle:             { ko: 'AI 성적분석',             en: 'AI Analysis'         },
  aiLastAnalyzed:      { ko: '마지막 분석 ',             en: 'Last analyzed '      },
  aiSubtitle:          { ko: 'Groq AI가 학업 데이터를 분석합니다',
                         en: 'Analyze your academic data with Groq AI'         },
  aiConsultSet:        { ko: '상담 입력됨',              en: 'Consultation set'    },
  aiConsultBtn:        { ko: '상담 내용',               en: 'Consultation'        },
  aiChangeKey:         { ko: 'API 키 변경',             en: 'Change Key'          },
  aiNeedKey:           { ko: 'API 키 필요',             en: 'API Key Required'    },
  aiAnalyzing:         { ko: '분석 중...',              en: 'Analyzing...'        },
  aiReanalyze:         { ko: '재분석',                 en: 'Re-analyze'          },
  aiStart:             { ko: 'AI 분석 시작',             en: 'Start Analysis'      },
  aiConsultTitle:      { ko: 'AI에게 상담하고 싶은 내용',   en: 'Consultation for AI' },
  aiConsultNote:       { ko: '— 분석 결과에 반영됩니다',    en: '— included in analysis' },
  aiConsultPh:         { ko: '예) 전공 성적이 낮은 편인데 대학원 진학이 가능할까요? / 취업을 위해 어떤 과목을 더 들어야 할까요?',
                         en: 'e.g. My major GPA is low — can I apply to grad school? / What courses should I take for employment?' },
  aiClear:             { ko: '초기화',                 en: 'Clear'               },
  aiKeyPh:             { ko: 'Groq API Key 입력  (https://console.groq.com/ - API keys - 키 발급받기)',
                         en: 'Enter Groq API Key  (https://console.groq.com/ → API Keys)'  },
  aiPressStart:        { ko: 'AI 분석 시작 버튼을 눌러주세요', en: 'Press the "Start Analysis" button' },
  aiEnterKey:          { ko: 'Groq API 키를 먼저 입력해주세요', en: 'Please enter your Groq API key first' },
  aiDesc:              { ko: '성적 데이터를 기반으로 강점 · 개선점 · 진로 추천을 분석합니다',
                         en: 'Analyze your strengths, improvements, and career paths from grade data' },
  aiRespLang:          { ko: '응답 언어:',              en: 'Response language:'  },
  aiLangKo:            { ko: '한국어',                 en: 'Korean'              },
  aiConsultIncluded:   { ko: '상담 내용 포함됨',          en: 'Consultation included'},
  aiAnalyzingMsg:      { ko: 'AI가 학업 데이터를 분석하는 중...', en: 'Analyzing academic data...' },
  aiWaitMsg:           { ko: '약 10~20초 소요됩니다',     en: 'This may take 10–20 seconds' },
  aiStrength:          { ko: '강점',                  en: 'Strength'            },
  aiImprovement:       { ko: '개선 포인트',             en: 'Improvement'         },
  aiGraduation:        { ko: '졸업 전망',              en: 'Graduation'          },
  aiGpaTrend:          { ko: '학기별 GPA 추이',          en: 'GPA Trend by Semester'},
  aiNoGradeData:       { ko: '성적 데이터 없음',          en: 'No grade data'       },
  aiGpaLabel:          { ko: '학기별 GPA · 누적 평균',     en: 'GPA · Avg'           },
  aiStudyStrat:        { ko: 'AI 학습 전략',             en: 'AI Study Strategies' },
  aiCareer:            { ko: '진로 추천',               en: 'Career Recommendation'},
  aiGradOutlook:       { ko: '졸업 전망',               en: 'Graduation Outlook'  },
  aiConsultResp:       { ko: 'AI 상담 답변',             en: 'AI Consultation Response' },
  aiQuestion:          { ko: '질문',                  en: 'Question'            },
  aiReport:            { ko: 'AI 종합 분석 리포트',        en: 'AI Comprehensive Report' },
  aiCurrentSem:        { ko: '현재',                  en: 'Current'             },

  // ── Board ──
  boardTitle:          { ko: '게시판',                 en: 'Board'               },
  boardNewPost:        { ko: '글쓰기',                 en: 'New Post'            },
  boardTrending:       { ko: '이번 주 화제글',           en: "This Week's Trending" },
  boardMyPosts:        { ko: '내 글',                  en: 'My Posts'            },
  boardMyPostsSub:     { ko: '내가 작성한 글',            en: 'Posts you wrote'     },
  boardSaved:          { ko: '저장글',                 en: 'Saved'               },
  boardSavedSub:       { ko: '북마크한 글',              en: 'Bookmarked'          },
  boardLiked:          { ko: '좋아요글',               en: 'Liked'               },
  boardLikedSub:       { ko: '좋아요한 글',              en: 'Posts you liked'     },
  boardCommented:      { ko: '댓글단 글',               en: 'Commented'           },
  boardCommentedSub:   { ko: '댓글 단 글',              en: 'Posts you commented on' },
  boardAllPosts:       { ko: '전체 글',                en: 'All Posts'           },
  boardAll:            { ko: '전체',                  en: 'All'                 },
  boardLatest:         { ko: '최신순',                 en: 'Latest'              },
  boardMostLiked:      { ko: '좋아요순',               en: 'Most Liked'          },
  boardSearch:         { ko: '검색...',               en: 'Search...'           },
  boardNoResults:      { ko: '검색 결과가 없습니다.',      en: 'No results found.'   },
  boardNoResultsSub:   { ko: '검색어를 다시 한 번 확인해 주세요', en: 'Please check your search term' },
  boardLoadMore:       { ko: '더 보기',                en: 'Load More'           },
  boardMyPostsPopup:   { ko: '내가 쓴 글',              en: 'My Posts'            },
  boardSavedPopup:     { ko: '저장한 글',               en: 'Saved Posts'         },
  boardLikedPopup:     { ko: '좋아요한 글',             en: 'Liked Posts'         },
  boardCommentedPopup: { ko: '댓글단 글',               en: 'Commented Posts'     },
  boardNoPosts:        { ko: '게시글이 없습니다.',        en: 'No posts.'           },
  boardWritePopup:     { ko: '게시글 작성',             en: 'New Post'            },
  boardTitlePh:        { ko: '제목을 입력하세요',         en: 'Enter title'         },
  boardContentPh:      { ko: '내용을 입력하세요',         en: 'Enter content'       },
  boardPosting:        { ko: '게시 중...',              en: 'Posting...'          },
  boardPost:           { ko: '게시',                  en: 'Post'                },
  boardComments:       { ko: '댓글',                  en: 'Comments'            },
  boardFirstComment:   { ko: '첫 번째 댓글을 남겨보세요.', en: 'Be the first to comment.' },
  boardMe:             { ko: '나',                    en: 'Me'                  },
  boardCommentPh:      { ko: '댓글을 입력하세요 ...',     en: 'Add a comment...'    },
  boardSubmit:         { ko: '등록',                  en: 'Submit'              },
  boardCollapse:       { ko: '접기',                  en: 'Collapse'            },
  boardMore:           { ko: '더 보기 (',              en: 'More ('              },
  boardBookmark:       { ko: '북마크',                 en: 'Bookmark'            },

  // ── Courses ──
  coursesTitle:        { ko: '수강신청 계획',            en: 'Course Plan'         },
  coursesCurriculum:   { ko: '표준이수모형',             en: 'Curriculum'          },
  coursesChangeImg:    { ko: '이미지 교체',              en: 'Change Image'        },
  coursesCurrImg:      { ko: '이수모형 이미지',            en: 'Curriculum Image'    },
  coursesDragDrop:     { ko: '클릭하거나 파일을 드래그하세요', en: 'Click or drag a file here' },
  coursesSemList:      { ko: '이번 학기 수강신청 목록',    en: "This Semester's Course List" },
  coursesEmpty:        { ko: '과목을 추가해보세요',        en: 'Add a course to get started' },
  coursesEnrolled:     { ko: '담김',                  en: 'Enrolled'            },
  coursesAddToCart:    { ko: '담기',                  en: 'Add to Cart'         },
  coursesTotal:        { ko: '학점계',                 en: 'Total Credits'       },
  coursesCrPlanned:    { ko: '학점 예정',               en: 'cr planned'          },
  coursesAfterCr:      { ko: '수강 후 학점',             en: 'Credits After Enroll'},
  coursesCurrent:      { ko: '현재',                  en: 'Current'             },
  coursesAfterEnroll:  { ko: '수강 후',                en: 'After'               },
  coursesAddPopup:     { ko: '과목 추가',               en: 'Add Course'          },
  coursesCourseName:   { ko: '과목명 *',               en: 'Course Name *'       },
  coursesCourseNamePh: { ko: '예: 기초 컴퓨터 프로그래밍', en: 'e.g. Intro to Programming' },
  coursesCategory:     { ko: '구분',                  en: 'Category'            },
  coursesCreditsLabel: { ko: '학점',                  en: 'Credits'             },
  coursesProf:         { ko: '교수명',                 en: 'Instructor'          },
  coursesProfPh:       { ko: '예: 홍길동',              en: 'e.g. Prof. Hong'     },
  coursesAddAction:    { ko: '추가하기',               en: 'Add'                 },
  coursesCrUnit:       { ko: ' 학점',                 en: ' cr'                 },
  coursesCurrSemPrefix:{ ko: '이번 학기 ',              en: 'This Sem: '          },

  // ── Dashboard 힌트 (동적 GPA 계산) ──
  dashYearUnit:        { ko: '년',                    en: ''                    },
  dashHintAvg:         { ko: '이번 학기 과목 평균 ',    en: 'Avg. '               },
  dashHintOrAbove:     { ko: ' 이상이면 목표 GPA ',     en: ' or above → target GPA ' },
  dashHintPossible:    { ko: ' 달성 가능',              en: ''                    },
  dashHintAlready:     { ko: '이미 목표 GPA 달성 중',   en: 'Already on track!'   },

  // ── Community Preview ──
  communityTitle:      { ko: '커뮤니티',               en: 'Community'           },
  communityViewMore:   { ko: '더보기',                 en: 'View More'           },
  communityNoPosts:    { ko: '게시글이 없습니다',        en: 'No posts yet'        },

  // ── Footer ──
  footerPrivacy:       { ko: '개인정보처리방침',         en: 'Privacy Policy'      },
  footerTerms:         { ko: '이용약관',                en: 'Terms of Service'    },
  footerDept:          { ko: '소프트웨어학부',           en: 'Dept. of Software'   },

  // ── 시간 포맷 ──
  timeMinAgo:          { ko: '분 전',                  en: 'm ago'               },
  timeHourAgo:         { ko: '시간 전',                en: 'h ago'               },
  timeDayAgo:          { ko: '일 전',                  en: 'd ago'               },
};

// 번역 함수: t(key, lang) => 해당 언어 텍스트
export function t(key: string, lang: Lang): string {
  return T[key]?.[lang] ?? T[key]?.ko ?? key;
}
